export const THEME = "github-dark-default";

export const SCOPE_COLORS: Record<string, string> = {
  "hljs-keyword": "#ff7b72",
  "hljs-built_in": "#ffa657",
  "hljs-type": "#ffa657",
  "hljs-literal": "#79c0ff",
  "hljs-number": "#79c0ff",
  "hljs-string": "#a5d6ff",
  "hljs-regexp": "#a5d6ff",
  "hljs-comment": "#8b949e",
  "hljs-title": "#d2a8ff",
  "hljs-function": "#d2a8ff",
  "hljs-attr": "#79c0ff",
  "hljs-attribute": "#79c0ff",
  "hljs-variable": "#ffa657",
  "hljs-property": "#79c0ff",
  "hljs-tag": "#7ee787",
  "hljs-name": "#7ee787",
  "hljs-selector-tag": "#7ee787",
  "hljs-meta": "#79c0ff",
  "hljs-symbol": "#79c0ff",
};

export const HLJS_BY_SHIKI: Record<string, string> = {
  tsx: "typescript",
  jsx: "javascript",
  jsonc: "json",
  shellscript: "bash",
  html: "xml",
  svelte: "xml",
  vue: "xml",
  toml: "ini",
  docker: "dockerfile",
};

export const LANG_BY_EXT: Record<string, string> = {
  ts: "typescript",
  mts: "typescript",
  cts: "typescript",
  tsx: "tsx",
  js: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  jsx: "jsx",
  json: "json",
  jsonc: "jsonc",
  py: "python",
  rb: "ruby",
  go: "go",
  rs: "rust",
  java: "java",
  c: "c",
  h: "c",
  cpp: "cpp",
  cc: "cpp",
  hpp: "cpp",
  cs: "csharp",
  php: "php",
  sh: "shellscript",
  bash: "shellscript",
  zsh: "shellscript",
  yml: "yaml",
  yaml: "yaml",
  toml: "toml",
  md: "markdown",
  html: "html",
  xml: "xml",
  svelte: "svelte",
  vue: "vue",
  css: "css",
  scss: "scss",
  less: "less",
  sql: "sql",
  lua: "lua",
  swift: "swift",
  kt: "kotlin",
  dart: "dart",
  ex: "elixir",
  exs: "elixir",
  zig: "zig",
  prisma: "prisma",
  graphql: "graphql",
  dockerfile: "docker",
  tf: "terraform",
};

export const TOKEN_CACHE_LIMIT = 5000;
